// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import ProductController from "./product_controller"
application.register("product", ProductController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)
